name: wtf_web
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_gradient_colors: ^2.1.1
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  flutter_bootstrap: ^2.0.0
  get: ^4.6.1
  expandable_page_view: ^1.0.10
  grouped_buttons: ^1.0.4
  syncfusion_flutter_sliders: ^19.4.55
  dotted_border: ^2.0.0+2
  rxdart: ^0.27.3
  carousel_slider: ^4.0.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.13
  awesome_loader: ^0.0.3
  lottie: ^1.2.2
  flutter_html: ^0.11.1
  video_player: ^2.2.4
  animated_size_and_fade: ^3.0.0
  smooth_page_indicator: ^1.0.0
  hover_effect: ^0.6.0
  equatable: ^2.0.3
  url_launcher: ^6.0.20
  cupertino_tabbar: ^2.0.0
  intl: ^0.17.0
  flash: ^2.0.3+2
  collapsible_sidebar: ^2.0.1+2
  # razorpay_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/home/
    - assets/fitness/
    - assets/gym/
    - assets/gym_details/
    - assets/nutrition/
    - assets/membership_details/
    - assets/partner/
    - assets/about_us/
    - assets/studio/
    - assets/membership/
    - assets/login/
    - assets/lottie/
    - assets/live_classes/
    - assets/signup/
    - assets/thanks/
    - assets/onboarding/
    - assets/html/
    - assets/profile/
